trigger: 
- main

stages:

- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      displayName: terrform toolinstall
      inputs:
        terraformVersion: 'latest'
  
    - task: TerraformTask@5
      displayName: terrform plan
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'PER-MSD-ZTAHIR_01(7ad68a7a-1c98-4cde-925e-da17234ab644)'
        backendAzureRmStorageAccountName: 'lokisopra'
        backendAzureRmContainerName: 'ruler-loki'
        backendAzureRmKey: 'my-tf-plan'
        